image: docker:stable

stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DH_REGISTRY_IMAGE: $DOCKER_USER/$CI_PROJECT_NAME

build:
  stage: build
  variables:
    PROJECT_NAME: "milobella"
    MODULE_NAME: ${CI_PROJECT_NAME}
    GITLAB_HOST: "gitlab.milobella.com"
    MODULE_DESCRIPTION: "Simple tool to manage a shopping list in a MongDB database."
  before_script:
    # Login to gitlab registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  tags: [docker,milobella]

release-image:
  stage: release
  before_script:
    - export APP_VERSION=$(cat VERSION.txt)
    # Login to gitlab registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # Login to docker hub
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    # Push to docker hub registry
    - docker tag $CONTAINER_TEST_IMAGE $DH_REGISTRY_IMAGE:latest
    - docker tag $CONTAINER_TEST_IMAGE $DH_REGISTRY_IMAGE:${APP_VERSION}
    - docker push $DH_REGISTRY_IMAGE:latest
    - docker push $DH_REGISTRY_IMAGE:${APP_VERSION}
    # Push to gitlab registry
    - docker tag $CONTAINER_TEST_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker tag $CONTAINER_TEST_IMAGE $CI_REGISTRY_IMAGE:${APP_VERSION}
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:${APP_VERSION}
  tags: [docker,milobella]
  only: [master]

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  before_script:
    - export APP_VERSION=$(cat VERSION.txt)
    - mkdir -p bin /etc/kubernetes
    # Configurate the kubectl command to request the minikube cluster
    - echo ${MINIKUBE_CLIENT_CRT} | base64 -d > /etc/kubernetes/minikube-client.crt
    - echo ${MINIKUBE_CLIENT_KEY} | base64 -d > /etc/kubernetes/minikube-client.key
    - mv helm/.kubeconfig /etc/kubernetes/.config
    - export KUBECONFIG=/etc/kubernetes/.config
    # Initialize helm client without tiller
    - helm init --client-only
  script:
    # Package the helm chart into a tgz repository
    - helm package helm/tool-shoppinglist --app-version=${APP_VERSION} --destination bin
    # Install/Upgrade the freshly packaged helm chart into the minikube cluster
    - helm upgrade --install tool-shoppinglist bin/tool-shoppinglist-*.tgz --debug --set image.tag=${APP_VERSION}
  tags: [docker,milobella]
  only: [master]