image: docker:stable

stages:
  - build
  - release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DH_REGISTRY_IMAGE: $DOCKER_USER/$CI_PROJECT_NAME

before_script:
  # Login to gitlab registry
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  # Login to docker hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

build:
  stage: build
  variables:
    PROJECT_NAME: "milobella"
    MODULE_NAME: ${CI_PROJECT_NAME}
    GITLAB_HOST: "gitlab.milobella.com"
    MODULE_DESCRIPTION: "Simple tool to manage a shopping list in a MongDB database."
  script:
  # Write the id_rsa private key into the good path
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  tags: [docker,milobella]

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    # Push to docker hub registry
    - docker tag $CONTAINER_TEST_IMAGE $DH_REGISTRY_IMAGE:latest
    - docker tag $CONTAINER_TEST_IMAGE $DH_REGISTRY_IMAGE:$(cat VERSION.txt)
    - docker push $DH_REGISTRY_IMAGE:latest
    - docker push $DH_REGISTRY_IMAGE:$(cat VERSION.txt)
    # Push to gitlab registry
    - docker tag $CONTAINER_TEST_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker tag $CONTAINER_TEST_IMAGE $CI_REGISTRY_IMAGE:$(cat VERSION.txt)
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$(cat VERSION.txt)
  tags: [docker,milobella]
  only: [master]


