include:
  - project: 'milobella/devops/ci-templates'
    file: '/templates/common-template.yml'

stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DH_REGISTRY_IMAGE: $DOCKER_USER/$CI_PROJECT_NAME
  PROJECT_NAME: "milobella"
  MODULE_NAME: ${CI_PROJECT_NAME}
  GITLAB_HOST: "milobella.com/gitlab"
  MODULE_DESCRIPTION: "Shopping list API lib."
  HELM_NAME: "tool-shoppinglist"
